
export const VENUES = [
    {
        name: "(le) poisson rouge",
        href: "https://lpr.com/",
        address: "158 Bleecker St",
        city: "New York",
        state: "New York",
        zip: "10012",
        image : [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Arlene's Grocery",
        href: "https://www.arlenesgrocery.net/",
        address: "95 Stanton St",
        city: "New York",
        state: "New York",
        zip: "10002",
        overallRating: '3/5',
        anonymityRating: '2/5',
        elevator: false,
        ramps: false,
        rampComment: "only first floor access, basement has stairs",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "one on first floor",
        overallComment: "no elevators, bands play in basement. Will have to be carried.",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Baby's All Right",
        href: "http://babysallright.com/",
        address: "146 Broadway",
        city: "Brooklyn",
        state: "New York",
        zip: "11211",
        rampComment: "single floor venue",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Brooklyn Bazaar",
        href: "https://bkbazaar.com/",
        address: "150 Greenpoint Ave",
        city: "Brooklyn",
        state: "New York",
        zip: "11222",
        overallRating: "4/5",
        anonymityRating: "1/5",
        elevator: false,
        ramps: false,
        rampComment: "only first floor access, 4 floor venue",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "one on first floor",
        overallComment: "no elevators, sometimes bands play fourth floor. Will have to be carried.",
        image: ["../assets/images/venues/Brooklyn Bazaar/BK-Bazaar-Outside.jpg"],
        baseImage: "https://i.imgur.com/Sc3UDZ1.jpg"
    },
    {
        name: "Brooklyn Bowl",
        href: "https://www.brooklynbowl.com/brooklyn/",
        address: "61 Wythe Ave",
        city: "Brooklyn",
        state: "New York",
        zip: "11249",
        overallRating: "5/5",
        anonymityRating: "5/5",
        elevator: false,    
        ramps: true,
        rampComment: "ramps anywhere you need to go",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "two accessible restrooms downstairs",
        overallComment: "first floor where bands play and bowling is all have ramps",
        image: [
            "https://i.imgur.com/kEtwwdE.jpg",
            "https://i.imgur.com/3fyYMSV.jpg",
            "https://i.imgur.com/u9UYwWL.jpg",
            "https://i.imgur.com/E1HjGP7.jpg",
            "https://i.imgur.com/42z4zwM.jpg",
            "https://i.imgur.com/qy5fW3X.jpg",
            "https://i.imgur.com/O8WljZn.jpg",
            "https://i.imgur.com/oz1lEW7.jpg",
            "https://i.imgur.com/7OiGG6c.jpg",
            "https://i.imgur.com/vkbk7mb.jpg",
            "https://i.imgur.com/yGuEG47.jpg",
            "https://i.imgur.com/CXf6VUo.jpg",
            "https://i.imgur.com/4RVEPzx.jpg",
            "https://i.imgur.com/7G70P2R.jpg",
            "https://i.imgur.com/XxSmp18.jpg",
            "https://i.imgur.com/KDheEK1.jpg",
            "https://i.imgur.com/rqlKoFa.jpg",
            "https://i.imgur.com/xkm3h2s.jpg",
            "https://i.imgur.com/AAqunjG.jpg",
            "https://i.imgur.com/V014M2V.jpg",
            "https://i.imgur.com/1UG1koq.jpg",
            "https://i.imgur.com/chHwA1B.jpg",  
            "https://i.imgur.com/kEtwwdE.jpg",
            "https://i.imgur.com/u9UYwWL.jpg",
        ],
        baseImage: "https://i.imgur.com/u9UYwWL.jpg"
    },
    {
        name: "Brooklyn Steel",
        href: "https://www.bowerypresents.com/venues/brooklyn-steel",
        address: "319 Frost Street",
        city: "Brooklyn",
        state: "NY",
        zip: "11222",
        overallRating: "5/5",
        anonymityRating: "4/5",
        elevator: true,
        ramps: true,
        rampComment: "accessible entrances",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Forest Hills Stadium",
        href: "http://foresthillsstadium.com/",
        address: "1 Tennis Place",
        city: "Queens",
        state: "NY",
        zip: "11375",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Great Hill (Central Park)",
        href: "http://www.centralparknyc.org/things-to-see-and-do/attractions/great-hill.html",
        address: "Great Hill",
        city: "New York",
        state: "NY",
        zip: "10025",
        overallRating: "3/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampComment: "very steep hills, call ahead for a space on a cart to be taken to the hill",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "portable and regular park ones available",
        overallComment: "request accomodation prior to events by calling 212.446.2242",
        image: [
            "https://i.imgur.com/KUX9y7E.jpg",
            "https://i.imgur.com/Rc9cjMG.jpg",
            "https://i.imgur.com/M71LC4G.jpg",
            "https://i.imgur.com/vMRA9T3.jpg",
            "https://i.imgur.com/DjHA3yK.jpg",
            "https://i.imgur.com/X07IXl2.jpg",
            "https://i.imgur.com/Ex4zpJh.jpg",
            "https://i.imgur.com/TEGQNed.jpg",
            "https://i.imgur.com/iHcVLgH.jpg",
            "https://i.imgur.com/qji5kF4.jpg",
            "https://i.imgur.com/kIgsMJq.jpg",
            "https://i.imgur.com/KtAZx0g.jpg",
        ],
        baseImage: "https://i.imgur.com/KUX9y7E.jpg"
    },
    {
        name: "Hammerstein Ballroom",
        href: "https://mc34.com/",
        address: "311 W 34th St",
        city: "New York",
        state: "New York",
        zip: "10001",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Industry City",
        href: "https://industrycity.com/",
        address: "220 36th St",
        city: "Brooklyn",
        state: "NY",
        zip: "11232",
        overallRating: "4/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampComment: "single floor venue with ramps in between buildings",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "large restrooms with accessible stalls",
        overallComment: "Large venue with 8 buildings total. To go from one end to the other would be a lot of weaving around ramps. Courtyard 1/2 is where the bandshell is and a little food. Can sit in the VIP to see the show.",
        image: [
            "https://i.imgur.com/zRHLqWb.jpg",
            "https://i.imgur.com/zKsZkr5.jpg",
            "https://i.imgur.com/7wCmsQQ.jpg",
            "https://i.imgur.com/ctFOJd6.jpg",
            "https://i.imgur.com/pLMph1K.jpg",
            "https://i.imgur.com/1BWtCBG.jpg",
            "https://i.imgur.com/IiCtFtg.jpg",
            "https://i.imgur.com/zPfnxAx.jpg",
            "https://i.imgur.com/A1Gh2yM.jpg",
            "https://i.imgur.com/M8KW93O.jpg",
        ],
        baseImage: "https://i.imgur.com/ctFOJd6.jpg"
    },
    {
        name: "Joe's Pub",
        href: "https://publictheater.org/programs/joes-pub/",
        address: "425 Lafayette Street",
        city: "New York",
        state: "NY",
        zip: "10003",
        overallRating: "4/5",
        anonymityRating: "3/5",
        elevator: false,
        ramps: true,
        rampComment: "single floor venue with ramps in between buildings",
        overallComment: "The website has good information: please contact us at 212.967.7555 (voice) or accessibility@publictheater.org.",
        image: [
            "https://i.imgur.com/wDzvuak.jpg",
            "https://i.imgur.com/zZM4TtY.jpg",
            "https://i.imgur.com/WSUunPW.jpg",
            "https://i.imgur.com/oPdIhNH.jpg"
        ],
        baseImage: "https://i.imgur.com/wDzvuak.jpg"
    },
    {
        name: "King's Theater",
        href: "http://www.kingstheatre.com/",
        address: "1027 Flatbush Ave",
        city: "Brooklyn",
        state: "NY",
        zip: "11226",
        elevator: false,
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "The Knitting Factory - Brooklyn",
        href: "https://bk.knittingfactory.com/",
        address: "361 Metropolitan Ave",
        city: "Brooklyn",
        state: "NY",
        zip: "11211",
        overallRating: "4/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampComment: "single floor venue with ramps",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "stall restrooms, not really fit for accessibility",
        overallComment: "one floor venue that's pretty small. Not hard to see the band even when sitting though there's some nice side spaces if having trouble. There's a step up outside for the bar area.",
        image: [
            "https://i.imgur.com/vqWRdqS.jpg",
            "https://i.imgur.com/Dzxi17z.jpg",
            "https://i.imgur.com/oXeuOn3.jpg",
            "https://i.imgur.com/4lcFpsw.jpg",
            "https://i.imgur.com/5W9Ar3m.jpg",
            "https://i.imgur.com/hlB6HLA.jpg",
            "https://i.imgur.com/GaWZJGN.jpg",
            "https://i.imgur.com/G2xJU22.jpg",
            "https://i.imgur.com/KljMvga.jpg",
            "https://i.imgur.com/UcfXu6L.jpg",
            "https://i.imgur.com/Ha8Z0u7.jpg",
            "https://i.imgur.com/PzFer6h.jpg",
            "https://i.imgur.com/BYWP3YA.jpg",
            "https://i.imgur.com/W7hTCWI.jpg",
            "https://i.imgur.com/HWcY0hU.jpg",
        ],
        baseImage: "https://i.imgur.com/vqWRdqS.jpg"
    },
    {
        name: "Market Hotel",
        href: "https://www.markethotel.org/",
        address: "1140 Myrtle Ave",
        city: "Brooklyn",
        state: "NY",
        zip: "11221",
        ramps: false,
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Music Hall of Williamsburg",
        href: "https://www.musichallofwilliamsburg.com/",
        address: "66 North 6th Street",
        city: "Brooklyn",
        state: "NY",
        zip: "11211",
        overallRating: "3/5",
        anonymityRating: "3/5",
        elevator: true,
        ramps: true,
        rampComment: "a lot of steps everywhere, but ramp and elevator access",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible stalls",
        overallComment: "multi-level venue, with access to view show above main floor",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Rockwood Music Hall",
        href: "http://www.rockwoodmusichall.com/",
        address: "196 Allen St",
        city: "New York",
        state: "NY",
        zip: "10002",
        overallRating: "4/5",
        anonymityRating: "2/5",
        elevator: true,
        ramps: true,
        rampComment: "shares elevator with restaurant next door, if going to stage 3, come early or call ahead. The other 2 stages are accessible.",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "large enough restrooms",
        overallComment: "Stage 2 is only accessible on Orchard St. Both stage 1 and 2 are one floor.",
        image: [
            "https://i.imgur.com/bJUi82a.jpg",
            "https://i.imgur.com/xHLYs84.jpg",
            "https://i.imgur.com/qOLzgds.jpg",
            "https://i.imgur.com/lsqDNdW.jpg",
            "https://i.imgur.com/PMV6IWX.jpg",
            "https://i.imgur.com/hTEQIaf.jpg",
            "https://i.imgur.com/B71h6Jc.jpg",
        ],
        baseImage: "https://i.imgur.com/hTEQIaf.jpg"
    },
    {
        name: "Rough Trade NYC",
        href: "https://www.roughtradenyc.com/",
        address: "64 N 9th St",
        city: "Brooklyn",
        state: "NY",
        zip: "11249",
        overallRating: "3/5",
        anonymityRating: "2/5",
        elevator: false,
        ramps: true,
        rampComment: "one floor venue with ramps, however there's no elevator access to balcony which helps to see better.",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible stalls",
        overallComment: "there is no elevator to the balcony and no place to be where it'd provide a nice view for someone in a chair if it's a packed show.",
        image: [
            "https://i.imgur.com/lBEQrOJ.jpg",
            "https://i.imgur.com/vKDh9YQ.jpg",
            "https://i.imgur.com/pxi7Lg6.jpg",
            "https://i.imgur.com/y5qxJbO.jpg",
            "https://i.imgur.com/jQxfTMh.jpg",
            "https://i.imgur.com/zPj6n1t.jpg",
            "https://i.imgur.com/LAyQxHG.jpg",
            "https://i.imgur.com/7NLQeYr.jpg",
            "https://i.imgur.com/yMbqjOj.jpg",
            "https://i.imgur.com/Nl2FJbr.jpg",
            "https://i.imgur.com/eTa8N8m.jpg",
            "https://i.imgur.com/oB9a8Cu.jpg",
            "https://i.imgur.com/GD08rLC.jpg",
            "https://i.imgur.com/A8YtYoY.jpg",
        ],
        baseImage: "https://i.imgur.com/lBEQrOJ.jpg"
    },
    {
        name: "Saint Vitus Bar",
        href: "https://www.saintvitusbar.com/",
        address: "1120 Manhattan Ave",
        city: "Brooklyn",
        state: "NY",
        zip: "11222",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Shea Stadium",
        href: "http://liveatsheastadium.com/",
        address: "20 Meadow St",
        city: "Brooklyn",
        state: "NY",
        zip: "11206",
        elevator: false,
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "Sunnyvale BK",
        href: "https://www.sunnyvalebk.com/",
        address: "1031 Grand St",
        city: "Brooklyn",
        state: "NY",
        zip: "11211",
        elevator: false,
        ramps: true,
        rampComment: "single floor venue",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "The Bell House",
        href: "https://www.thebellhouseny.com/",
        address: "149 7th St",
        city: "Brooklyn",
        state: "NY",
        zip: "11215",
        elevator: false,
        ramps: true,
        rampComment: "single floor venue",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "The Gutter - Brooklyn",
        href: "https://www.thegutterbrooklyn.com/",
        address: "200 N 14th St",
        city: "Brooklyn",
        state: "NY",
        zip: "11211",
        overallRating: "3/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampComment: "music on main floor, bowling has steps",
        restrooms: true,
        restroomKey: true,
        restroomsComment: "get bathroom key, one accessible bathroom",
        overallComment: "There is no ramp to go bowling and there are several stairs to climb",
        image: [
            "https://i.imgur.com/q07qT6c.jpg",
            "https://i.imgur.com/UkPRmd6.jpg",
            "https://i.imgur.com/ItQ6mKc.jpg",
            "https://i.imgur.com/zLrnX4N.jpg",
            "https://i.imgur.com/VAgdM2J.jpg",
        ],
        baseImage: "https://i.imgur.com/zLrnX4N.jpg"
    },
    {
        name: "The Kingsland Bar",
        href: "http://kingslandbk.com/",
        address: "269 Norman Ave",
        city: "Brooklyn",
        state: "NY",
        zip: "11222",
        elevator: false,
        ramps: false,
        rampComment: "single floor venue, but one step to get in",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    },
    {
        name: "The Mercury Lounge",
        href: "http://www.mercuryeastpresents.com/mercurylounge",
        address: "217 E Houston St",
        city: "New York",
        state: "NY",
        zip: "10002",
        overallRating: "4/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: false,
        rampComment: "one step up to get in, single floor after",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible bathrooms, small area to open the door next to the bar.",
        overallComment: "one floor venue with a decent view if sitting down. There are benches along the sides.",
        image: [
            "https://i.imgur.com/ahTaJ6Z.jpg",
            "https://i.imgur.com/tSRiaPs.jpg",
            "https://i.imgur.com/wThSQgI.jpg",
            "https://i.imgur.com/DMcPn1Q.jpg",
            "https://i.imgur.com/4pihtaL.jpg",
            "https://i.imgur.com/0BtYuoL.jpg",
            "https://i.imgur.com/9RP8xVy.jpg",
            "https://i.imgur.com/KW8tMgL.jpg",
            "https://i.imgur.com/KkwQHXI.jpg",
        ],
        baseImage: "https://i.imgur.com/tSRiaPs.jpg"
    },  
    {
        name: "Union Hall",
        href: "https://www.unionhallny.com/",
        address: "702 Union St",
        city: "Brooklyn",
        state: "NY",
        zip: "11215",
        overallRating: "2/5",
        anonymityRating: "1/5",
        elevator: false,
        ramps: false,
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible bathrooms, small area to open the door next to the bar.",
        overallComment: "this venue is not accessible. There's a step up to get in and an accessible bathroom on the main floor. But shows are downstairs with no elevator access. You will have to be carried.",
        image: [
            "https://i.imgur.com/2WytNrD.jpg",
            "https://i.imgur.com/JWFckSQ.jpg",
            "https://i.imgur.com/ljze6DV.jpg",
            "https://i.imgur.com/nexaxfS.jpg",
            "https://i.imgur.com/i4DQUIR.jpg",
            "https://i.imgur.com/p5GEQiD.jpg",
            "https://i.imgur.com/QoPFJAB.jpg",
            "https://i.imgur.com/We3Rwqe.jpg",
            "https://i.imgur.com/DdPr5DT.jpg",
            "https://i.imgur.com/bG4yMmp.jpg",
            "https://i.imgur.com/xN9Fsfz.jpg",
            "https://i.imgur.com/pDY4ItN.jpg",
            "https://i.imgur.com/U1t82GO.jpg",
            "https://i.imgur.com/hjgH4ml.jpg",
            "https://i.imgur.com/aIE21mt.jpg"
        ],
        baseImage: "https://i.imgur.com/aIE21mt.jpg"
    }, 
    {
        name: "Union Pool",
        href: "https://www.union-pool.com/",
        address: "484 Union Ave",
        city: "Brooklyn",
        state: "NY",
        zip: "11211",
        overallRating: "3/5",
        anonymityRating: "3/5",
        elevator: false,
        ramps: true,
        rampComment: "one step up to get in, one floor after",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "not labeled, though large. Doors open in",
        overallComment: "backyard music free outside all summer, one level venue inside",
        image: [
            "https://i.imgur.com/c1zKzBf.jpg",
            "https://i.imgur.com/Qhj5Zy6.jpg",
            "https://i.imgur.com/5P95nwu.jpg",
            "https://i.imgur.com/iDQRw5E.jpg",
            "https://i.imgur.com/vrvuA5p.jpg",
            "https://i.imgur.com/eBKydrP.jpg",
            "https://i.imgur.com/e6We7nY.jpg",
            "https://i.imgur.com/1ddQ29h.jpg",
            
        ],
        baseImage: "https://i.imgur.com/c1zKzBf.jpg"
    },
    {
        name: "Webster Hall",
        href: "https://websterhall.com/",
        address: "125 E. 11th Street",
        city: "New York",
        state: "NY",
        zip: "10003",
        image: [],
        baseImage: "https://i.imgur.com/piN9lPP.png"
    }
]

export default VENUES;

