
const VENUES = [
    {
        venue: 'Brooklyn Bazaar',
        href: 'https://bkbazaar.com/',
        address: '150 Greenpoint Ave, Brooklyn, NY 11222',
        overallRating: '4/5',
        anonymityRating: '1/5',
        elevator: false,
        ramps: false,
        rampComment: 'only first floor access, 4 floor venue',
        restrooms: true,
        restroomKey: false,
        restroomsComment: 'one on first floor',
        overallComment: 'no elevators, sometimes bands play fourth floor. Will have to be carried.',
        image: './assets/images/venues/Brooklyn Bazaar/BK-Bazaar-Outside.jpg',
    },
    {
        venue: 'Brooklyn Bowl',
        href: 'https://www.brooklynbowl.com/brooklyn/',
        address: '61 Wythe Ave, Brooklyn, NY 11249',
        overallRating: '5/5',
        anonymityRating: '5/5',
        elevator: false,
        ramps: true,
        rampElComment: 'ramps anywhere you need to go',
        restrooms: true,
        restroomKey: false,
        restroomsComment: 'two accessible restrooms downstairs',
        overallComment: 'first floor where bands play and bowling is all have ramps',
        image: './asssets/images/venues/Union Pool/Union-Pool2.jpg',
    },
    {
        venue: 'Union Pool',
        href: 'https://www.union-pool.com/',
        address: '484 Union Ave, Brooklyn, NY 11211',
        overallRating: '3/5',
        anonymityRating: '3/5',
        elevator: false,
        ramps: true,
        rampElComment: 'one step up to get in, one floor after',
        restrooms: true,
        restroomKey: false,
        restroomsComment: 'not labeled, though large. Doors open in',
        overallComment: 'backyard music free outside all summer, one level venue inside',
        image: './asssets/images/venues/Union Pool/Union-Pool1.HEIC',
    },
]

