
const VENUES = [
    {
        venue: "(le) poisson rouge",
        href: "https://lpr.com/",
        address: "158 Bleecker St, New York, NY 10012",
    },
    {
        venue: "Arlene's Grocery",
        href: "https://www.arlenesgrocery.net/",
        address: "95 Stanton St, New York, NY 10002",
        overallRating: '3/5',
        anonymityRating: '2/5',
        elevator: false,
        ramps: false,
        rampComment: "only first floor access, basement has stairs",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "one on first floor",
        overallComment: "no elevators, bands play in basement. Will have to be carried.",
    },
    {
        venue: "Baby's All Right",
        href: "http://babysallright.com/",
        address: "146 Broadway, Brooklyn, NY 11211",
        rampComment: "single floor venue",
    },
    {
        venue: "Brooklyn Bazaar",
        href: "https://bkbazaar.com/",
        address: "150 Greenpoint Ave, Brooklyn, NY 11222",
        overallRating: "4/5",
        anonymityRating: "1/5",
        elevator: false,
        ramps: false,
        rampComment: "only first floor access, 4 floor venue",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "one on first floor",
        overallComment: "no elevators, sometimes bands play fourth floor. Will have to be carried.",
        image: "./assets/images/venues/Brooklyn Bazaar/BK-Bazaar-Outside.jpg",
    },
    {
        venue: "Brooklyn Bowl",
        href: "https://www.brooklynbowl.com/brooklyn/",
        address: "61 Wythe Ave, Brooklyn, NY 11249",
        overallRating: "5/5",
        anonymityRating: "5/5",
        elevator: false,
        ramps: true,
        rampElComment: "ramps anywhere you need to go",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "two accessible restrooms downstairs",
        overallComment: "first floor where bands play and bowling is all have ramps",
        image: "./assets/images/venues/Brooklyn Bowl/Brooklyn-Bowl21.jpg",
    },
    {
        venue: "Brooklyn Steel",
        href: "https://www.bowerypresents.com/venues/brooklyn-steel",
        address: "319 Frost Street, Brooklyn, NY 11222",
        overallRating: "5/5",
        anonymityRating: "4/5",
        elevator: true,
        ramps: true,
        rampElComment: "accessible entrances",
    },
    {
        venue: "Forest Hills Stadium",
        href: "http://foresthillsstadium.com/",
        address: "1 Tennis Place, Queens, NY 11375",
    },
    {
        venue: "Great Hill (Central Park)",
        href: "http://www.centralparknyc.org/things-to-see-and-do/attractions/great-hill.html",
        address: "Great Hill, New York, NY 10025",
        overallRating: "3/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampElComment: "very steep hills, call ahead for a space on a cart to be taken to the hill",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "portable and regular park ones available",
        overallComment: "request accomodation prior to events by calling 212.446.2242",
        image: "./assets/images/venues/Central Park-Great Hill/Great-Hill9.jpg",
    },
    {
        venue: "Hammerstein Ballroom",
        href: "https://mc34.com/",
        address: "311 W 34th St, New York, NY 10001",
    },
    {
        venue: "Industry City",
        href: "https://industrycity.com/",
        address: "220 36th St, Brooklyn, NY 11232",
        overallRating: "4/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampElComment: "single floor venue with ramps in between buildings",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "large restrooms with accessible stalls",
        overallComment: "Large venue with 8 buildings total. To go from one end to the other would be a lot of weaving around ramps. Courtyard 1/2 is where the bandshell is and a little food. Can sit in the VIP to see the show.",
        image: "./assets/images/venues/Industry City/Industry-City9.jpg",
    },
    {
        venue: "Joe's Pub",
        href: "https://publictheater.org/programs/joes-pub/",
        address: "425 Lafayette Street New York, NY 10003",
        overallRating: "4/5",
        anonymityRating: "3/5",
        elevator: false,
        ramps: true,
        rampElComment: "single floor venue with ramps in between buildings",
        overallComment: "The website has good information: please contact us at 212.967.7555 (voice) or accessibility@publictheater.org.",
        image: "./assets/images/venues/Joe's Pub/Joes-Pub1.jpg",
    },
    {
        venue: "King's Theater",
        href: "http://www.kingstheatre.com/",
        address: "1027 Flatbush Ave, Brooklyn, NY 11226",
        elevator: false,
    },
    {
        venue: "The Knitting Factory - Brooklyn",
        href: "https://bk.knittingfactory.com/",
        address: "361 Metropolitan Ave, Brooklyn, NY 11211",
        overallRating: "4/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampElComment: "single floor venue with ramps",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "stall restrooms, not really fit for accessibility",
        overallComment: "one floor venue that's pretty small. Not hard to see the band even when sitting though there's some nice side spaces if having trouble. There's a step up outside for the bar area.",
        image: "./assets/images/venues/Knitting Factory/Knitting-Factory14.jpg",
    },
    {
        venue: "Market Hotel",
        href: "https://www.markethotel.org/",
        address: "1140 Myrtle Ave, Brooklyn, NY 11221",
        ramps: false,
    },
    {
        venue: "Music Hall of Williamsburg",
        href: "https://www.musichallofwilliamsburg.com/",
        address: "66 North 6th Street, Brooklyn, NY 11211",
        overallRating: "3/5",
        anonymityRating: "3/5",
        elevator: true,
        ramps: true,
        rampElComment: "a lot of steps everywhere, but ramp and elevator access",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible stalls",
        overallComment: "multi-level venue, with access to view show above main floor",
    },
    {
        venue: "Rockwood Music Hall",
        href: "http://www.rockwoodmusichall.com/",
        address: "196 Allen St, New York, NY 10002",
        overallRating: "4/5",
        anonymityRating: "2/5",
        elevator: true,
        ramps: true,
        rampElComment: "shares elevator with restaurant next door, if going to stage 3, come early or call ahead. The other 2 stages are accessible.",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "large enough restrooms",
        overallComment: "Stage 2 is only accessible on Orchard St. Both stage 1 and 2 are one floor.",
        image: "./assets/images/venues/Rockwood/Rockwood6.jpg",
    },
    {
        venue: "Rough Trade NYC",
        href: "https://www.roughtradenyc.com/",
        address: "64 N 9th St, Brooklyn, NY 11249",
        overallRating: "3/5",
        anonymityRating: "2/5",
        elevator: false,
        ramps: true,
        rampElComment: "one floor venue with ramps, however there's no elevator access to balcony which helps to see better.",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible stalls",
        overallComment: "there is no elevator to the balcony and no place to be where it'd provide a nice view for someone in a chair if it's a packed show.",
        image: "./assets/images/venues/Rough Trade/Rough-TradeBK14.jpg",
    },
    {
        venue: "Saint Vitus Bar",
        href: "https://www.saintvitusbar.com/",
        address: "1120 Manhattan Ave, Brooklyn, NY 11222",
    },
    {
        venue: "Shea Stadium",
        href: "http://liveatsheastadium.com/",
        address: "20 Meadow St, Brooklyn, NY 11206",
        elevator: false,
    },
    {
        venue: "Sunnyvale BK",
        href: "https://www.sunnyvalebk.com/",
        address: "1031 Grand St, Brooklyn, NY 11211",
        elevator: false,
        ramps: true,
        rampElComment: "single floor venue",
    },
    {
        venue: "The Bell House",
        href: "https://www.thebellhouseny.com/",
        address: "149 7th St, Brooklyn, NY 11215",
        elevator: false,
        ramps: true,
        rampElComment: "single floor venue",
    },
    {
        venue: "The Gutter - Brooklyn",
        href: "https://www.thegutterbrooklyn.com/",
        address: "200 N 14th St, Brooklyn, NY 11211",
        overallRating: "3/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: true,
        rampElComment: "music on main floor, bowling has steps",
        restrooms: true,
        restroomKey: true,
        restroomsComment: "get bathroom key, one accessible bathroom",
        overallComment: "There is no ramp to go bowling and there are several stairs to climb",
        image: "./assets/images/venues/The Gutter-BK/Gutter-BK5.jpg",
    },
    {
        venue: "The Kingsland Bar",
        href: "http://kingslandbk.com/",
        address: "269 Norman Ave, Brooklyn, NY 11222",
        elevator: false,
        ramps: false,
        rampElComment: "single floor venue, but one step to get in",
    },
    {
        venue: "The Mercury Lounge",
        href: "http://www.mercuryeastpresents.com/mercurylounge",
        address: "217 E Houston St, New York, NY 10002",
        overallRating: "4/5",
        anonymityRating: "4/5",
        elevator: false,
        ramps: false,
        rampElComment: "one step up to get in, single floor after",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible bathrooms, small area to open the door next to the bar.",
        overallComment: "one floor venue with a decent view if sitting down. There are benches along the sides.",
        image: "./assets/images/venues/Mercury Lounge/Mercury-Lounge5.jpg",
    },  
    {
        venue: "Union Hall",
        href: "https://www.unionhallny.com/",
        address: "702 Union St, Brooklyn, NY 11215",
        overallRating: "2/5",
        anonymityRating: "1/5",
        elevator: false,
        ramps: false,
        restrooms: true,
        restroomKey: false,
        restroomsComment: "accessible bathrooms, small area to open the door next to the bar.",
        overallComment: "this venue is not accessible. There's a step up to get in and an accessible bathroom on the main floor. But shows are downstairs with no elevator access. You will have to be carried.",
        image: "./assets/images/venues/Union Hall/Union-Hall7.jpg",
    }, 
    {
        venue: "Union Pool",
        href: "https://www.union-pool.com/",
        address: "484 Union Ave, Brooklyn, NY 11211",
        overallRating: "3/5",
        anonymityRating: "3/5",
        elevator: false,
        ramps: true,
        rampElComment: "one step up to get in, one floor after",
        restrooms: true,
        restroomKey: false,
        restroomsComment: "not labeled, though large. Doors open in",
        overallComment: "backyard music free outside all summer, one level venue inside",
        image: "./assets/images/venues/Union Pool/Union-Pool8.jpg",
    },
    {
        venue: "Webster Hall",
        href: "https://websterhall.com/",
        address: "125 E. 11th Street, New York, NY 10003",
    },
]

